### ISSUE TITLE
OAuthSignatureCheckingFilter prevents developers to use http

### ISSUE THREAD

**Issue by davidchau** [AppDirect/service-integration-sdk#141]
OAuthSignatureCheckingFilter.java is transforming the protocol in the signature base string from http to https.
This prevent the signature tu be validated if the oauth signature was perform using http.

Instead, to proper support protocol change (from https to http) developer should add the following spring configuration:
```
server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
```

This will activate RemoteIpValve.java which will take care of the protocol replacement using the `x-forwarded-proto` header
